/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author vinis
 */
public class Iinicio extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPneu
     */
    public Iinicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCarros = new javax.swing.JButton();
        jButtonPneus = new javax.swing.JButton();
        jButton2Acessorios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(null);

        jButtonCarros.setText("Carros ");
        jButtonCarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCarrosMouseClicked(evt);
            }
        });
        jButtonCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarrosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCarros);
        jButtonCarros.setBounds(120, 210, 75, 23);

        jButtonPneus.setText("Pneus");
        jButtonPneus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPneusMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonPneus);
        jButtonPneus.setBounds(260, 210, 75, 23);

        jButton2Acessorios.setText("Acessorios");
        jButton2Acessorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2AcessoriosMouseClicked(evt);
            }
        });
        jButton2Acessorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2AcessoriosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2Acessorios);
        jButton2Acessorios.setBounds(190, 260, 86, 23);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadstros");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 20, 50, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\vinis\\OneDrive\\Documentos\\NetBeansProjects\\Concecionaria\\src\\Concecionaria-Imagem\\LogoInicial.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, -70, 720, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCarrosActionPerformed

    private void jButtonCarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCarrosMouseClicked
        JanelaCarro obj  = new JanelaCarro();
        obj.setVisible(true);
    }//GEN-LAST:event_jButtonCarrosMouseClicked

    private void jButtonPneusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPneusMouseClicked
        JanelaPneus obj = new JanelaPneus();
        obj.setVisible(true);
    }//GEN-LAST:event_jButtonPneusMouseClicked

    private void jButton2AcessoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2AcessoriosMouseClicked
        JanelaAcessorios obj = new JanelaAcessorios();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton2AcessoriosMouseClicked

    private void jButton2AcessoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2AcessoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2AcessoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iinicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2Acessorios;
    private javax.swing.JButton jButtonCarros;
    private javax.swing.JButton jButtonPneus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
